### ISSUE TITLE
Unable to install requirements on Windows 

### ISSUE THREAD

**Issue by nirnachmani** [teticio/Deej-AI#28]
When trying to install requirements on Windows 10 via ' pip install -r requirements.txt' I receive the following error:

ERROR: Could not find a version that satisfies the requirement tensorflow==2.2.0 (from versions: 2.5.0, 2.5.1, 2.5.2, 2.5.3, 2.6.0rc0, 2.6.0rc1, 2.6.0rc2, 2.6.0, 2.6.1, 2.6.2, 2.6.3, 2.6.4, 2.6.5, 2.7.0rc0, 2.7.0rc1, 2.7.0, 2.7.1, 2.7.2, 2.7.3, 2.8.0rc0, 2.8.0rc1, 2.8.0, 2.8.1, 2.8.2, 2.9.0rc0, 2.9.0rc1, 2.9.0rc2, 2.9.0, 2.9.1)
ERROR: No matching distribution found for tensorflow==2.2.0

I attempted to install a later version of tensorflow which requires later versions of other packages but run into many errors later on.

**Comment by teticio** [comment]
Sorry for the delay in getting back to you!! I missed this one. I expect it is due to the version of Python you are using. The use it with the packages as they are pinned, it is best to use Python 3.8.
