### ISSUE TITLE
Suggestion for data source: lastfm or listenbrainz

### ISSUE THREAD

**Issue by Sohalt** [teticio/Deej-AI#36]
Hi, really cool project!
I have 2 more suggestions for data sources to train the model on.
https://last.fm and https://listenbrainz.org/ allow users to track the songs they are listening to (and allow you to query that information). While you don't get playlists, the plays are tagged with a timestamp, so you could look for consecutive plays of songs and split e.g. when there is a break of more than 30min between songs.

**Comment by teticio** [comment]
Thanks! I will check that out. Although what was special about Spotify was being able to download a 30s MP3 sample. I remember loking into Last.FM at the time (I used to use it years ago). Maybe you can find a way to leverage them?
