### ISSUE TITLE
Add separate requirement file for MacOS (M1/M2)

### ISSUE THREAD

**Issue by mathiassname** [teticio/Deej-AI#45]
I have some trouble with the requirements on my MacBook with M2 processor. I modify the requirements.

Add a separate requirement file for MacOS:

```
dash
tqdm
mutagen
Flask
spotipy
librosa
dash_core_components==0.47.0
dash_html_components==0.16.0
dash_daq==0.1.4
pandas
numpy
dash_html_components
Pillow
tensorflow-macos
numba
```

Reference: https://developer.apple.com/metal/tensorflow-plugin/

**Comment by teticio** [comment]
Thanks for this but I'd rather not do this. This is specific to tensorflow and Mac M1/2. I don't have a way of testing on say a non M1 mac. But people will find this issue if they search for it so thanks!
