### ISSUE TITLE
No module named 'audiodiffusion.audio_encoder'; 'audiodiffusion' is not a package

### ISSUE THREAD

**Issue by stunlocked1** [teticio/Deej-AI#48]
```
ModuleNotFoundError
No module named 'audiodiffusion.audio_encoder'; 'audiodiffusion' is not a package
AttributeError: partially initialized module 'audiodiffusion' has no attribute '__path__' (most likely due to a circular import)

During handling of the above exception, another exception occurred:

  File "F:\Stuff\Programming\libs\audiodiffusion.py", line 3, in <module>
    from audiodiffusion.audio_encoder import AudioEncoder
  File "F:\Stuff\Programming\libs\audiodiffusion.py", line 3, in <module>
    from audiodiffusion.audio_encoder import AudioEncoder
ModuleNotFoundError: No module named 'audiodiffusion.audio_encoder'; 'audiodiffusion' is not a package
```

**Comment by teticio** [comment]
What were you doing to get this error? If you were running the `tf_to_pt.py` script you need to `pip install audiodiffusion`. But I'm not sure you would really need to run this script. Have a look at my other repo `auto-diffusion` if you are interested in audio diffusion.

**Comment by stunlocked1** [comment]
> What were you doing to get this error? If you were running the `tf_to_pt.py` script you need to `pip install audiodiffusion`. But I'm not sure you would really need to run this script. Have a look at my other repo `auto-diffusion` if you are interested in audio diffusion.

I did copied everything from hugging face. pip install audiodiffusion into python 3.8 installation, then
from audiodiffusion.audio_encoder import AudioEncoder

audio_encoder = AudioEncoder.from_pretrained("teticio/audio-encoder")
audio_encoder.encode(<list of audio files>)

**Comment by teticio** [comment]
OK, I was confused because you have posted the issue here, rather in the audiodiffusion repo.  I have reproduced the steps above just now in a fresh virtualenv and it works fine. Try with Python 3.10

**Comment by stunlocked1** [comment]
i see the issue was that my file was named audiodiffusion.py and it imported itself instead of actual package
