### ISSUE TITLE
KeyError generating mp3 mix or playlist

### ISSUE THREAD

**Issue by friki67** [teticio/Deej-AI#54]
Hello! I've just discovered this and I'm trying it!
I set up an Ubuntu LXC container, installed all the things included the requirements.txt, and launched the scan process with success. Now I have my Picker directory with all the data.

`python3 MP3ToVec.py Pickles mp3tovec --scan /home/ubuntu/deejai/ayj/`

I'm using a small set of files (52 mp3) to test this. Then I created a tracks.txt file, containing just

```
'06 - Ella Fitzgerald - Cheek To Cheek.mp3'
'07 - Michael Buble - Come Fly With Me.mp3'
'08 - Paolo Nutini - Coming Up Easy.mp3'
'09 - Karen Souza - Creep.mp3'
```

or

```
'/home/ubuntu/deejai/ayj/06 - Ella Fitzgerald - Cheek To Cheek.mp3'
'/home/ubuntu/deejai/ayj/07 - Michael Buble - Come Fly With Me.mp3'
'/home/ubuntu/deejai/ayj/08 - Paolo Nutini - Coming Up Easy.mp3'
'/home/ubuntu/deejai/ayj/09 - Karen Souza - Creep.mp3'
```
But when I try

`python3 Join_the_dots.py Pickles/mp3tovecs/mp3tovec.p --input tracks.txt mix.mp3 6`

I always get the KeyError

```
Traceback (most recent call last):
  File "/home/ubuntu/deejai/Deej-AI/Join_the_dots.py", line 129, in <module>
    playlist = join_the_dots(input_tracks, n=n, noise=noise)
  File "/home/ubuntu/deejai/Deej-AI/Join_the_dots.py", line 67, in join_the_dots
    start_vec = mp3tovec[start]
KeyError: "'06 - Ella Fitzgerald - Cheek To Cheek.mp3'"

What am I doing wrong?
```
Trying to do `python3 Deej-A.I.py Pickles mp3tovec`  or trying to create the playlist gives me this error:

```
Traceback (most recent call last):
  File "/home/ubuntu/deejai/Deej-AI/Deej-A.I.py", line 32, in <module>
    app = dash.Dash()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/dash/dash.py", line 236, in __init__
    self.server.before_first_request(self._setup_server)
AttributeError: 'Flask' object has no attribute 'before_first_request'. Did you mean: '_got_first_request'?
```
Just to add some more info.

**Comment by teticio** [comment]
I think your first problem is due to the single quotes in the text file. Can you try removing them?

Regarding the second problem it is likely you have the wrong version of Flask installed. Can you do

pip list | grep -I flask

**Comment by friki67** [comment]
Hello. I get
```
Flask                        2.3.2
Flask-Compress               1.13
```

**Comment by teticio** [comment]
Sorry about this, but it looks like the `requirements.txt` file had the wrong `Flask` version. I also had to pin `markupsafe==2.0.1`. This is the problem with maintaining old versions... Please reinstall your dependencies from the updated `requirements.txt` file and let me know if this fixes it.

**Comment by friki67** [comment]
Working!

Thank you very much!

**Comment by teticio** [comment]
Great! Thanks for taking the time to report an issue and try it out. Hope you get some good results.
