### ISSUE TITLE
Analyzing local music?

### ISSUE THREAD

**Issue by Chaphasilor** [teticio/Deej-AI#62]
Hi!  

I've been interested in this project for quite some time now, and I finally have enough free time to look into it properly.  
It's great that this is so simple to use with Spotify, however, my use case is slightly different. I would like to integrate this with my Jellyfin server to get suggestions for my local music. As far as I can tell, you've split up the different processing steps in a way that *should* allow analyzing local tracks instead of downloaded previews, but I think I need to get my Jellyfin track IDs in there somehow, instead of the Spotify IDs. Exporting to m3u would work fine for the start.

I also found the ["Try it out for yourself" section](https://github.com/teticio/Deej-AI#try-it-out-for-yourself) in the readme, and that seems to be mostly working, but I believe that is using outdated code, right? The rewritten version only works for Spotify I'd guess.

Could you give me pointers on how and where to ideally modify the code, if necessary? Or is there a way to hook into the process, e.g. by generating some supplementary csv files based on my Jellyfin library?  
Thanks in advance!

**Comment by teticio** [comment]
The code should still work for your local files. What error do you get? I did rewrite the code for generating playlists more efficiently but that is in the deej-ai.online-app project which is linked to Spotify as you say. There is a more efficient way of generating the vectors using the calc_mp3tovecs and calc_tfidf scripts in the train directory. They were written with Spotify preview mp3s in mind, but will work with any (flat) directory of mp3s (MP3ToVec.py will work with nested directories).

**Comment by Chaphasilor** [comment]
Not getting any error so far, other than the CLI not accepting "foreign" tracks when the web tool does. I was just looking to re-use part of the integration work that you did for Spotify :)

I'll give it a go, maybe it's easier than expected ^^

**Comment by teticio** [comment]
Sorry for the delay.

Yes, the JoinTheDots.py script is expecting you to give it an already analyzed mp3, and the only way of knowing that is to pass the "key". The DeejAI.py script that runs the Flask webapp has some extra code which analyzes any mp3 track on the fly and then builds the playlist based on this, so you could take this code. But, as I say, these scripts are a bit old and clunky. If you are going to do anything at all serious, I would take inspiration from the train/calc_mp3tovecs.py, train/calc_tfidf.py and deej-ai.online/backend/deejai.py scripts. You would need to use the first two to pre-calculate the vectors for your entire library and you could adapt the functions to analyze a track and create playlists etc from the latter. I regret not having made the deejai.py code a bit more modular by separating out the Spotify dependencies, but I haven't really had the time to do that.

Good luck!
