### ISSUE TITLE
for some reason spotify breaks the tracks scraping after 4900~, it ip banned me.

### ISSUE THREAD

**Issue by togersonS** [teticio/Deej-AI#64]
Starting with playlist 4920

No response or error after that, i've tried getting a new client id and a new playlist but now its at 
Starting with playlist 0

That concludes spottily banned me for using this script.

**Comment by togersonS** [comment]
i tried get users from it how do i use a proxy with get users i think it also ban ip from it

**Comment by teticio** [comment]
I didn't add the proxy there, as you have to give a cookie, which is traceable to your spotify user. I figured it was best to be less devious in this case, but it wouldn't be difficult to adapt the code (see the example in get_playlists.py)
