### ISSUE TITLE
Developer terms restrictions?

### ISSUE THREAD

**Issue by dasbts** [teticio/Deej-AI#67]
Hi, 

Great work with this. I have been building a bit on the side of this for about a year on some ideas, but then I noticed the terms of service for development in Spotify API, do you have any better knowledge around this? 
https://developer.spotify.com/terms#section-iv-restrictions

General restrictions.

    Misuse of the Spotify Platform. Do not misuse the Spotify Platform, including by
        using the Spotify Platform or any Spotify Content to train a machine learning or AI model or otherwise ingesting Spotify Content into a machine learning or AI model;

10. Governing Law

Notwithstanding any other provision in the Developer Agreement, this Appendix shall be governed by, and interpreted in accordance with, the laws of Sweden.

Cheers 
dasbts

**Comment by teticio** [comment]
Oh, I never saw that... Oops! I guess it is a question of scale. If my thing became super successful and starting eating their lunch, maybe they would wave that bit of paper at me.

**Comment by teticio** [comment]
Would love to know what you are up to with your project. Feel free to email.
