### ISSUE TITLE
Skips all MP3s

### ISSUE THREAD

**Issue by JavaScythe** [teticio/Deej-AI#79]
I have ffmpeg, gstreamer, librosa, soundfile, audioread, yet none of my mp3s are processed.
Running Arch Linux, installed dependencies via pacman (some from AUR)

<img width="325" alt="image" src="https://github.com/teticio/Deej-AI/assets/57111248/dc936231-00ac-48e3-a875-4b6c9adbb6e3">

How do I get this working

**Comment by teticio** [comment]
Sorry to hear that. Best advice I can give you is to change the try / except block that skips the mp3s to raise the exception or at least log the error. That should give you a clue as to what is failing.
